baseurl = "/"
title = "Brighton PostgreSQL Users Group"
author = "Michael Bryant"
paginate = 10
theme = "BluestNight"
PygmentsCodeFences = true
PygmentsStyle = "monokai"
enableRobotsTXT = true

[outputs]
    home = ["HTML", "CSS", "JSON", "RSS"]
    section = ["HTML", "RSS"]

[Params]
    tagline = "The sea elephants"
    description = "Elephants by the sea." # Description of your site
    authorbox = false
    author = "Brighton PostgreSQL"
    post_navigation = false
    thumbnail = "img/marvin.png"
    favicon = "img/marvin.ico"
    thumbnail_radius = "10%"

[Params.iubenda]
    id = ""
    legal_only = false

[Params.iubenda.pro]
    enable_pro = false
    site_id = ""
    enable_cookie_policy = true
    disable_footer_link = true
    prior_consent = true

[Params.background]
    src = "img/header_hi.jpg"
    medium_src = "img/header_md.jpg"
    small_src = "img/header_lo.jpg"
    fit_width = false
    tile = false

[Params.widgets]
    search = true
    recent_articles = true
    categories = true
    tags = true
    tags_counter = true
    patreon = ""

[Params.social]
    github = "orgs/brightonpg/"
    facebook = "brightonpg/"

[Params.color]
    page_background = "#e2e2e2"
    main_background = "#e2e2e2"
    alt_background = "#e2e2e2"
    main_text = "#000000"
    alt_text = "#000000"
    accent = "#2c8cef"
    accent_text = "#e2e2e2"
    
[menu]
  