baseurl = "/"
title = "Brighton PostgreSQL Users Group"
languageCode = "en-gb"
paginate = "5" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "UA-51824212-2" # Enable Google Analytics by entering your tracking id



[Params]
    subtitle = "The sea elephants" # Subtitle of your site
    description = " This is the brighton postgresql users group website" # Description of your site
    opengraph = true
    readmore = false # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = false
    post_navigation = true
    postSections = ["post"]


[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
    social_twitter = "postgres_btn"
    social_github = "brightonpg"



[[menu.main]]
    name = "Blog"
    pre = "<i class='fa fa-heart'></i>"
    weight = 2
    identifier = "blog"
    url = "/post/"


[[menu.main]]
    name = "Youtube channel"
    pre = "<i class='fa fa-heart'></i>"
    weight = 3
    identifier = "youtube"
    url = "https://www.youtube.com/channel/UCgr5Iv9eJYN2Piy9oYkn6jw"

[[menu.main]]
        name = "Slack"
        pre = "<i class='fa fa-heart'></i>"
        weight = 4
        identifier = "slack"
        url = "https://pgbrighton.slack.com"
